### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by redox** [galdor/algolia-proxy#1]
Hey @galdor,

I'm working at Algolia and stumble upon your project \o/ I was wondering why you had to build such a backend proxy for Algolia. Is it for security purpose?

Let me know, I would be happy to assist you :)

**Comment by galdor** [comment]
I built it because it was asked as a technical test for my job interview at
Algolia :)

-- 
Nicolas Martyanoff
http://snowsyn.net
khaelin@gmail.com

**Comment by redox** [comment]
> I built it because it was asked as a technical test for my job interview at
> Algolia :)

Oh 😂  I should have synced with the team /o\ Good luck then!
